apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-setter
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caas:resource-setter
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caas:resource-setter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: caas:resource-setter
subjects:
  - kind: ServiceAccount
    name: resource-setter
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: resource-setter
  namespace: kube-system
  labels:
    xxx-label: resource-setter
spec:
  selector:
    matchLabels:
      xxx-label: resource-setter
  template:
    metadata:
      labels:
        xxx-label: resource-setter
    spec:
      containers:
        - name: process-plugin
          image: docker.io/library/ds-processer
          imagePullPolicy: IfNotPresent
          ##--rootfs needs to be set to the root of the cgroupfs hierarchy used by Kubelet for workloads
          command: [ "/ds-processer", "--configs=/etc/ds-config", "--rootfs=/rootfs/sys/fs/cgroup/devices/kubepods"]
          resources:
            requests:
              cpu: "10m"
          volumeMounts:
            - name: time-mount
              mountPath: /etc/localtime
              readOnly: true
            - mountPath: /etc/ds-config
              name: task-config
            ## -- do not mount kubepods under /sys to avoid circular linking
            - mountPath: /rootfs/sys/fs/cgroup/devices/kubepods
              name: kubepods
            - mountPath: /var/lib/kubelet/device-plugins/
              name: checkpointfile
              readOnly: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
      volumes:
        - name: time-mount
          hostPath:
            path: /etc/localtime
        ## resourceSetter parses the Kubelet checkpoint file for Device allocations
        - name: checkpointfile
          hostPath:
            path: /var/lib/kubelet/device-plugins/
        - name: kubepods
          hostPath:
            path: /sys/fs/cgroup/devices/kubepods
        ## The instance configuration files need to be mounted here
        - name: task-config
          configMap:
            name: task-configmap
      serviceAccountName: resource-setter

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: task-configmap
  namespace: kube-system
data:
  config-test-a.yaml: |
    apps: 
      xxx: 
    nodeSelector:
      node-role.kubernetes.io/node:
      node-role.kubernetes.io/master:
      #kubernetes.io/hostname: xxx

  config-test-b.yaml: |
    apps:
      xxx: 
    nodeSelector:
      node-role.kubernetes.io/node:
      node-role.kubernetes.io/master:
      #kubernetes.io/hostname: xxx